# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: tour
    url: tour
    weight: 10
  - name: news
    url: post
    weight: 20
  - name: people
    url: people
    weight: 30
  - name: publication
    url: publication
    weight: 50
  - name: contact
    url: #contact
    weight: 60
#  - name: event
#    url: event
#    weight: 40
